<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Orquesta workflow should continue if with item step fails</title>
    <link>https://forum.stackstorm.com/t/orquesta-workflow-should-continue-if-with-item-step-fails/1586</link>
    <description>Hi,

I have a simple workflow iterating over an array of URLs and querying them via core.http by using with.

      Query_URLs:
        with:
          items: &lt;% ctx().url_list %&gt;
        action: core.http
        input:
          url: &lt;% item() %&gt;
          method: &quot;PUT&quot;
          body: ...

Now I have the case that one called URL returns 404 error and therefore this action fails, but also interrupts all other queries and the whole workflow fails.

How can I configure it to continue even if one iteration fails?

Thanks.</description>
    
    <lastBuildDate>Mon, 08 Mar 2021 08:18:35 +0000</lastBuildDate>
    <category>Workflows</category>
    <atom:link href="https://forum.stackstorm.com/t/orquesta-workflow-should-continue-if-with-item-step-fails/1586.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>Orquesta workflow should continue if with item step fails</title>
        <dc:creator><![CDATA[wingi]]></dc:creator>
        <description><![CDATA[
            <p>Thanks, for your response. This is what I also recognized so far.<br>
Is there anything planned to enhance this situation?<br>
Is it useful to open a git issue as enhancement request, or is already something in place?</p>
          <p><a href="https://forum.stackstorm.com/t/orquesta-workflow-should-continue-if-with-item-step-fails/1586/3">Read full topic</a></p>
        ]]></description>
        <link>https://forum.stackstorm.com/t/orquesta-workflow-should-continue-if-with-item-step-fails/1586/3</link>
        <pubDate>Mon, 08 Mar 2021 08:18:35 +0000</pubDate>
        <guid isPermaLink="false">forum.stackstorm.com-post-1586-3</guid>
        <source url="https://forum.stackstorm.com/t/orquesta-workflow-should-continue-if-with-item-step-fails/1586.rss">Orquesta workflow should continue if with item step fails</source>
      </item>
      <item>
        <title>Orquesta workflow should continue if with item step fails</title>
        <dc:creator><![CDATA[arms11]]></dc:creator>
        <description><![CDATA[
            <p>By virtue of the workflow engine works, single failure at any given step will bring the workflow to stop. The only way to handle or continue is to add handler for failure by using when &lt;% failed() %&gt;. Though, this is not feasible in the <code>with-items</code> at the time of writing. The entire loop is finished and then only the flow proceeds to the next step. If possible, you might want to consider making this call from python-script with loop or shell-script making curl calls where you have handle on each request and continue the iteration while logging cases that fail. Hope that helps.</p>
          <p><a href="https://forum.stackstorm.com/t/orquesta-workflow-should-continue-if-with-item-step-fails/1586/2">Read full topic</a></p>
        ]]></description>
        <link>https://forum.stackstorm.com/t/orquesta-workflow-should-continue-if-with-item-step-fails/1586/2</link>
        <pubDate>Fri, 05 Mar 2021 15:30:58 +0000</pubDate>
        <guid isPermaLink="false">forum.stackstorm.com-post-1586-2</guid>
        <source url="https://forum.stackstorm.com/t/orquesta-workflow-should-continue-if-with-item-step-fails/1586.rss">Orquesta workflow should continue if with item step fails</source>
      </item>
      <item>
        <title>Orquesta workflow should continue if with item step fails</title>
        <dc:creator><![CDATA[wingi]]></dc:creator>
        <description><![CDATA[
            <p>Hi,</p>
<p>I have a simple workflow iterating over an array of URLs and querying them via core.http by using with.</p>
<pre><code>  Query_URLs:
    with:
      items: &lt;% ctx().url_list %&gt;
    action: core.http
    input:
      url: &lt;% item() %&gt;
      method: "PUT"
      body: ...
</code></pre>
<p>Now I have the case that one called URL returns 404 error and therefore this action fails, but also interrupts all other queries and the whole workflow fails.</p>
<p>How can I configure it to continue even if one iteration fails?</p>
<p>Thanks.</p>
          <p><a href="https://forum.stackstorm.com/t/orquesta-workflow-should-continue-if-with-item-step-fails/1586/1">Read full topic</a></p>
        ]]></description>
        <link>https://forum.stackstorm.com/t/orquesta-workflow-should-continue-if-with-item-step-fails/1586/1</link>
        <pubDate>Fri, 05 Mar 2021 14:29:33 +0000</pubDate>
        <guid isPermaLink="false">forum.stackstorm.com-post-1586-1</guid>
        <source url="https://forum.stackstorm.com/t/orquesta-workflow-should-continue-if-with-item-step-fails/1586.rss">Orquesta workflow should continue if with item step fails</source>
      </item>
  </channel>
</rss>
