<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:discourse="http://www.discourse.org/" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Pack Management - StackStorm Support (ARCHIVED)</title>
    <link>https://forum.stackstorm.com/c/core-st2-platform-issues/pack-management-issues/12</link>
    <description>Topics in the &#39;Pack Management&#39; category </description>
    
      <lastBuildDate>Wed, 04 Aug 2021 15:24:13 +0000</lastBuildDate>
      <atom:link href="https://forum.stackstorm.com/c/core-st2-platform-issues/pack-management-issues/12.rss" rel="self" type="application/rss+xml" />
        <item>
          <title>In st2 k8s deployment, getting `File does not exist` - while running script on remote server using custom pack</title>
          <dc:creator><![CDATA[mohan28]]></dc:creator>
          <category>Pack Management</category>
          <description><![CDATA[
            <p>ST2 version: 3.5</p>
<p>While trying to run the script on the remote server, getting the below error:</p>
<p><strong>Inside st2client:</strong><br>
$st2 run samplepack.run_remote_script<br>
<strong>error: Failed copying content to remote boxes. Local path /opt/stackstorm/packs/samplepack/actions/touch_test.sh does not exist.</strong><br>
failed: true<br>
return_code: 255<br>
succeeded: false<br>
traceback: "  File “/opt/stackstorm/st2/lib/python3.6/site-packages/remote_runner/remote_script_runner.py”, line 50, in _run<br>
copy_results = self._copy_artifacts(remote_action)<br>
File “/opt/stackstorm/st2/lib/python3.6/site-packages/remote_runner/remote_script_runner.py”, line 108, in _copy_artifacts<br>
mode=file_mode,<br>
File “/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/runners/parallel_ssh.py”, line 177, in put<br>
raise Exception(“Local path %s does not exist.” % local_path)<br>
"</p>
<h2>
<a name="action-1" class="anchor" href="https://forum.stackstorm.com#action-1"></a>Action:</h2>
<p>runner_type: “remote-shell-script”<br>
description: “remote shell runner”<br>
enabled: true<br>
name: run_remote_script<br>
pack: st2testclassic<br>
entry_point: “touch_test.sh”<br>
parameters:<br>
cmd:<br>
required: true<br>
type: string<br>
default: “date”<br>
username:<br>
required: true<br>
type: string<br>
default: “xxxx”<br>
password:<br>
required: true<br>
type: string<br>
default: “xxxx”<br>
hosts:<br>
type: “string”<br>
description: “Address of the syslog server”<br>
required: true<br>
default: “<a href="http://xxx.com" rel="noopener nofollow ugc">xxx.com</a>”<br>
experimental:<br>
immutable: true<br>
default: true</p>
<p>But the script is present, as shwon below in the st2client :<br>
</p><div class="lightbox-wrapper"><a class="lightbox" href="https://aws1.discourse-cdn.com/standard10/uploads/stackstorm/original/1X/3162cea22613aefdd8e9a062e3b576bbe570e1f3.jpeg" data-download-href="/uploads/short-url/72T5xJceGHgEpzxllFbt5t8g72X.jpeg?dl=1" title="Screenshot 2021-08-04 at 8.42.51 PM" rel="noopener nofollow ugc"><img src="https://aws1.discourse-cdn.com/standard10/uploads/stackstorm/optimized/1X/3162cea22613aefdd8e9a062e3b576bbe570e1f3_2_690x109.jpeg" alt="Screenshot 2021-08-04 at 8.42.51 PM" data-base62-sha1="72T5xJceGHgEpzxllFbt5t8g72X" width="690" height="109" srcset="https://aws1.discourse-cdn.com/standard10/uploads/stackstorm/optimized/1X/3162cea22613aefdd8e9a062e3b576bbe570e1f3_2_690x109.jpeg, https://aws1.discourse-cdn.com/standard10/uploads/stackstorm/optimized/1X/3162cea22613aefdd8e9a062e3b576bbe570e1f3_2_1035x163.jpeg 1.5x, https://aws1.discourse-cdn.com/standard10/uploads/stackstorm/optimized/1X/3162cea22613aefdd8e9a062e3b576bbe570e1f3_2_1380x218.jpeg 2x" data-small-upload="https://aws1.discourse-cdn.com/standard10/uploads/stackstorm/optimized/1X/3162cea22613aefdd8e9a062e3b576bbe570e1f3_2_10x10.png"></a></div><p></p>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://forum.stackstorm.com/t/in-st2-k8s-deployment-getting-file-does-not-exist-while-running-script-on-remote-server-using-custom-pack/1798">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/in-st2-k8s-deployment-getting-file-does-not-exist-while-running-script-on-remote-server-using-custom-pack/1798</link>
          <pubDate>Wed, 04 Aug 2021 15:24:13 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1798</guid>
          <source url="https://forum.stackstorm.com/t/in-st2-k8s-deployment-getting-file-does-not-exist-while-running-script-on-remote-server-using-custom-pack/1798.rss">In st2 k8s deployment, getting `File does not exist` - while running script on remote server using custom pack</source>
        </item>
        <item>
          <title>Stackstorm 3.5 - LDAP ,st2 pack install fails</title>
          <dc:creator><![CDATA[nithinsubbaraj]]></dc:creator>
          <category>Pack Management</category>
          <description><![CDATA[
            <p>Hi Team,</p>
<p>Need help in resolving the LDAP error.</p>
<p>On stackstorm 3.5 able to use the ldap by modifying the configuration in /etc/st2/st2.conf</p>
<p>Able to list the packs but not able to install the pack with LDAP account</p>
<p>####<a class="hashtag" href="https://forum.stackstorm.com/tag/error">#<span>error</span></a> #########<br>
Installation may take a while for packs with many items.</p>
<pre><code>    [ succeeded ] init_task
    [ succeeded ] download_pack
    [ succeeded ] make_a_prerun
    [ succeeded ] get_pack_dependencies
    [ succeeded ] check_dependency_and_conflict_list
    [ succeeded ] install_pack_requirements
    [ succeeded ] get_pack_warnings
    [  failed   ] register_pack
</code></pre>
<p>##############</p>
<p>stderr: "st2.actions.python.St2RegisterAction: DEBUG    Calling client method “register” with kwargs “{‘types’: [‘all’], ‘packs’: [‘ansible’]}”<br>
/opt/stackstorm/st2/lib/python3.6/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host ‘<a href="http://qc1udatast204.abacus-us.com" rel="noopener nofollow ugc">qc1udatast204.abacus-us.com</a>’. Adding certificate verification is strongly advised. See: <a href="https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings" class="inline-onebox" rel="noopener nofollow ugc">Advanced Usage - urllib3 2.0.0.dev0 documentation</a><br>
InsecureRequestWarning,<br>
Traceback (most recent call last):<br>
File “/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py”, line 395, in <br>
obj.run()<br>
File “/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py”, line 214, in run<br>
output = action.run(**self._parameters)<br>
File “/opt/stackstorm/packs/packs/actions/pack_mgmt/register.py”, line 79, in run<br>
format_func=format_result,<br>
File “/opt/stackstorm/packs/packs/actions/pack_mgmt/register.py”, line 155, in _run_client_method<br>
result = method(**method_kwargs)<br>
File “/opt/stackstorm/st2/lib/python3.6/site-packages/st2client/models/core.py”, line 42, in decorate<br>
return func(*args, **kwargs)<br>
File “/opt/stackstorm/st2/lib/python3.6/site-packages/st2client/models/core.py”, line 630, in register<br>
self.handle_error(response)<br>
File “/opt/stackstorm/st2/lib/python3.6/site-packages/st2client/models/core.py”, line 195, in handle_error<br>
response.raise_for_status()<br>
File “/opt/stackstorm/st2/lib/python3.6/site-packages/requests/models.py”, line 943, in raise_for_status<br>
raise HTTPError(http_error_msg, response=self)<br>
requests.exceptions.HTTPError: 404 Client Error: Not Found<br>
Unable to retrieve detailed message from the HTTP response. expected value at line 1 column 1: line 1 column 1 (char 0)<br>
for url: <a href="https://host.company.com/v1/packs/register" rel="noopener nofollow ugc">https://host.company.com/v1/packs/register</a></p>
<p>####################</p>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://forum.stackstorm.com/t/stackstorm-3-5-ldap-st2-pack-install-fails/1797">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/stackstorm-3-5-ldap-st2-pack-install-fails/1797</link>
          <pubDate>Wed, 04 Aug 2021 13:01:09 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1797</guid>
          <source url="https://forum.stackstorm.com/t/stackstorm-3-5-ldap-st2-pack-install-fails/1797.rss">Stackstorm 3.5 - LDAP ,st2 pack install fails</source>
        </item>
        <item>
          <title>How to create a new runner</title>
          <dc:creator><![CDATA[User42]]></dc:creator>
          <category>Pack Management</category>
          <description><![CDATA[
            <p>Hi,</p>
<p>I want to create a new runner, Where can i find the doc to help me for that ?</p>
<p>Thank You</p>
            <p><small>3 posts - 2 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/how-to-create-a-new-runner/1790">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/how-to-create-a-new-runner/1790</link>
          <pubDate>Wed, 28 Jul 2021 18:14:18 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1790</guid>
          <source url="https://forum.stackstorm.com/t/how-to-create-a-new-runner/1790.rss">How to create a new runner</source>
        </item>
        <item>
          <title>Downgrading stackstom from 3.5 to 3.4 facing issue</title>
          <dc:creator><![CDATA[nithinsubbaraj]]></dc:creator>
          <category>Pack Management</category>
          <description><![CDATA[
            <p>Hi Team,</p>
<p>We have installed latest version of stackstorm pack st2 3.5.0, on Python 3.6.8 on our linux 8 server ,when we try to downgrade the server to 3.4.1 ,we are facing the below error.</p>
<p>Earlier:<br>
st2 --version<br>
st2 3.5.0, on Python 3.6.8</p>
<p>Now:<br>
st2 --version<br>
st2 3.4.1, on Python 3.6.8</p>
<p>The error we are facing is<br>
st2 pack list<br>
ERROR: (‘Connection aborted.’, ConnectionResetError(104, ‘Connection reset by peer’))<br>
st2 pack install jira<br>
ERROR: (‘Connection aborted.’, ConnectionResetError(104, ‘Connection reset by peer’))</p>
<p>Logs:<br>
Traceback (most recent call last):<br>
File “/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/metrics/base.py”, line 228, in metrics_initialize<br>
METRICS = get_plugin_instance(PLUGIN_NAMESPACE, cfg.CONF.metrics.driver)<br>
File “/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/util/loader.py”, line 223, in get_plugin_instance<br>
namespace=namespace, name=name, invoke_on_load=invoke_on_load<br>
File “/opt/stackstorm/st2/lib/python3.6/site-packages/stevedore/driver.py”, line 61, in <strong>init</strong><br>
warn_on_missing_entrypoint=warn_on_missing_entrypoint<br>
File “/opt/stackstorm/st2/lib/python3.6/site-packages/stevedore/named.py”, line 89, in <strong>init</strong><br>
self._init_plugins(extensions)<br>
File “/opt/stackstorm/st2/lib/python3.6/site-packages/stevedore/driver.py”, line 113, in _init_plugins<br>
(self.namespace, name))<br>
stevedore.exception.NoMatches: No ‘st2common.metrics.driver’ driver found, looking for ‘noop’</p>
<p>During handling of the above exception, another exception occurred:</p>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://forum.stackstorm.com/t/downgrading-stackstom-from-3-5-to-3-4-facing-issue/1783">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/downgrading-stackstom-from-3-5-to-3-4-facing-issue/1783</link>
          <pubDate>Mon, 19 Jul 2021 11:23:21 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1783</guid>
          <source url="https://forum.stackstorm.com/t/downgrading-stackstom-from-3-5-to-3-4-facing-issue/1783.rss">Downgrading stackstom from 3.5 to 3.4 facing issue</source>
        </item>
        <item>
          <title>Ansible Pack Installation fails</title>
          <dc:creator><![CDATA[Phill93]]></dc:creator>
          <category>Pack Management</category>
          <description><![CDATA[
            <p>Hello,</p>
<p>I have a strange problem. I am trying to install the Ansible Pack on a new Stackstorm instance. The process always aborts at the action “SetupVirtualEnvironmentAction”, the error message “unable to execute ‘x86_64-linux-gnu-gcc’: No such file or directory” indicates that the runner is not able to find the gcc under /usr/bin/.</p>
<p>The installation for pykerberos runs with the root user and the system Python without problems.</p>
<p>Greetings</p>
<p>Phill93</p>
            <p><small>2 posts - 2 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/ansible-pack-installation-fails/1777">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/ansible-pack-installation-fails/1777</link>
          <pubDate>Mon, 12 Jul 2021 13:52:34 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1777</guid>
          <source url="https://forum.stackstorm.com/t/ansible-pack-installation-fails/1777.rss">Ansible Pack Installation fails</source>
        </item>
        <item>
          <title>Keeping HA nodes in sync (non k8s)</title>
          <dc:creator><![CDATA[minsis]]></dc:creator>
          <category>Pack Management</category>
          <description><![CDATA[
            <p>I have multiple clusters and multiple nodes in each one. In the documentation it suggest keeping the packs and virutalenv in sync with something like Ansible but there’s no suggestions on how one should do this. Any high-level suggestions on how to do this?</p>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://forum.stackstorm.com/t/keeping-ha-nodes-in-sync-non-k8s/1744">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/keeping-ha-nodes-in-sync-non-k8s/1744</link>
          <pubDate>Wed, 23 Jun 2021 19:41:38 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1744</guid>
          <source url="https://forum.stackstorm.com/t/keeping-ha-nodes-in-sync-non-k8s/1744.rss">Keeping HA nodes in sync (non k8s)</source>
        </item>
        <item>
          <title>How do I access config from remote-script?</title>
          <dc:creator><![CDATA[guymatz]]></dc:creator>
          <category>Pack Management</category>
          <description><![CDATA[
            <p>Hi!  How do I access a pack’s config from a remote-shell-script?</p>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://forum.stackstorm.com/t/how-do-i-access-config-from-remote-script/1732">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/how-do-i-access-config-from-remote-script/1732</link>
          <pubDate>Tue, 08 Jun 2021 20:09:50 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1732</guid>
          <source url="https://forum.stackstorm.com/t/how-do-i-access-config-from-remote-script/1732.rss">How do I access config from remote-script?</source>
        </item>
        <item>
          <title>Unable to connect to oracle using sql pack</title>
          <dc:creator><![CDATA[sanvaibhav]]></dc:creator>
          <category>Pack Management</category>
          <description><![CDATA[
            <p>I have created a sql.yaml to setup connection for oracle as below<br>
connections:<br>
oracle:<br>
host: databaseIpAddress<br>
username: username<br>
password: password<br>
database: dbServiceName<br>
drivername: oracle</p>
<p>But, I am receiving error like<br>
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-12505: TNS:listener does not currently know of SID given in connect descriptor<br>
(Background on this error at: <a href="http://sqlalche.me/e/14/4xp6" rel="noopener nofollow ugc">http://sqlalche.me/e/14/4xp6</a>)</p>
<p>how do i setup oracle connection correctly ? pl suuggest.</p>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://forum.stackstorm.com/t/unable-to-connect-to-oracle-using-sql-pack/1690">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/unable-to-connect-to-oracle-using-sql-pack/1690</link>
          <pubDate>Wed, 12 May 2021 11:03:16 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1690</guid>
          <source url="https://forum.stackstorm.com/t/unable-to-connect-to-oracle-using-sql-pack/1690.rss">Unable to connect to oracle using sql pack</source>
        </item>
        <item>
          <title>Installing packs from multiple private repos using Deploy keys...how to do more than one?</title>
          <dc:creator><![CDATA[willowhawk]]></dc:creator>
          <category>Pack Management</category>
          <description><![CDATA[
            <p>(note I already looked <a href="https://forum.stackstorm.com/t/how-to-install-pack-from-private-git-repository-using-ssh-when-deployed-on-docker/1500">here</a> and <a href="https://docs.stackstorm.com/packs.html#installing-packs-from-private-repositories" rel="noopener nofollow ugc">here</a> and did not see a resolution)</p>
<p>I am creating some proprietary workflows and actions along with some colleagues and we’re storing them in our organization’s GitHub in separate repos.</p>
<p>In order to use the <code>st2 pack install ssh://git@github.com:_GHUSER_/_REPO_</code> convention, for a Private repository, it requires a valid SSH key pair with access to the repo stored in the <code>root</code> user’s SSH config.</p>
<p>This works great for a single repo using a Deploy Key.  Or for multiple repos using an actual GH user account with an SSH key that you also install on the ST2 server instance.</p>
<p>In cases where you don’t want to use a personal SSH key on a shared server running the ST2 instance, it appears there is no way to support multiple Private repo’s using Deploy Keys without needing to comment out all other Deploy keys in the <code>~/.ssh/config</code> file before running the <code>st2 pack install</code> command.</p>
<p>The problem is that SSH will offer up all the keys it knows about, and <a href="http://github.com" rel="noopener nofollow ugc">github.com</a> will happily accept the very first key that works, and thus will only be able to install from a private repo that uses that specific key.  And for the record, you can only use a Deploy key on one specific repo in all of github land.</p>
<p>I was hoping to find a way to pass an IdentityFIle parameter to the <code>packs.download</code> action step of the <code>packs.install</code> workflow, but no dice.</p>
<p>Anyone have thoughts on this?  I’m going to look at using SSL tokens instead, but that’s a bit less secure since it will show up in logs since it becomes part of the URL.</p>
            <p><small>5 posts - 2 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/installing-packs-from-multiple-private-repos-using-deploy-keys-how-to-do-more-than-one/1672">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/installing-packs-from-multiple-private-repos-using-deploy-keys-how-to-do-more-than-one/1672</link>
          <pubDate>Sun, 02 May 2021 05:23:12 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1672</guid>
          <source url="https://forum.stackstorm.com/t/installing-packs-from-multiple-private-repos-using-deploy-keys-how-to-do-more-than-one/1672.rss">Installing packs from multiple private repos using Deploy keys...how to do more than one?</source>
        </item>
        <item>
          <title>How can I ONLY see actions, sensors and rules that are in the pack?</title>
          <dc:creator><![CDATA[ereT20]]></dc:creator>
          <category>Pack Management</category>
          <description><![CDATA[
            <p>At my company we are trying to configure StackStorm to be a tool for normal (non-programmer) coworkers to be able to build workflows using the workflow editor. The idea is we would have us programmers create a pack of actions, rules and sensors of the common tasks a normal user would use.</p>
<p>We would like to simplify the UI as much as possible and only display a single pack for them to drag items from. I cannot seem to make StackStorm ONLY display from the custom pack. It either displays all actions or none.</p>
<p>Here is what I have tried so far.</p>
<ul>
<li>I have created a pack using the steps here under “Creating Your First Pack” <a href="https://docs.stackstorm.com/reference/packs.html#creating-your-first-pack" class="inline-onebox" rel="noopener nofollow ugc">Create and Contribute a Pack — StackStorm 3.4.0 documentation</a>.</li>
</ul>
<pre><code class="lang-auto"># /opt/stackstorm/packs/twenty20_solutions/pack.yaml
ref: twenty20_solution
name: Twenty20 Solutions
description: Workflow automation toolbox
keywords:
- twenty20
- solutions
version: 0.0.1
python_versions:
- "3"
author: Twenty20 Solutions
email: test@test.com
</code></pre>
<ul>
<li>I enabled RBAC in the st2.conf</li>
</ul>
<pre><code class="lang-auto">[rbac]
enable = True
backend = default
</code></pre>
<ul>
<li>I created a role called the normal role</li>
</ul>
<pre><code class="lang-auto"># /opt/stackstorm/rbac/roles/normal.yaml
---
name: "normal"
description: "allowed ui workflow editor access"
enabled: true
permission_grants:
# - permission_types: # commented global permissions
# - "pack_list"
# - "action_list"
- resource_uid: "pack:twenty20_solutions"
permission_types:
- "pack_view"
- resource_uid: "action:twenty20_solutions"
permission_types:
- "action_view"
</code></pre>
<ul>
<li>
<p>I created a user called “nock”</p>
</li>
<li>
<p>I assigned the user nock to the role of normal</p>
</li>
</ul>
<pre><code class="lang-auto"># /opt/stackstorm/rbac/assignments/nock.yaml
---
username: "nock"
description: "trying to get this to work"
enabled: true
roles:
- "normal"
</code></pre>
<p>After changes to the role, I run <code>st2-apply-rbac-definitions --config-file=/etc/st2/st2.conf</code></p>
<pre><code class="lang-auto">eric@eric:/etc/st2$ st2-apply-rbac-definitions --config-file=/etc/st2/st2.conf
2021-04-27 17:08:45,323 INFO [-] Connecting to database "st2" @ "127.0.0.1:27017" as user "stackstorm".
2021-04-27 17:08:45,328 INFO [-] Successfully connected to database "st2" @ "127.0.0.1:27017" as user "stackstorm".
2021-04-27 17:08:45,484 INFO [-] Loading role definitions from "/opt/stackstorm/rbac/roles/"
2021-04-27 17:08:45,628 INFO [-] Loading user role assignments from "/opt/stackstorm/rbac/assignments/"
2021-04-27 17:08:45,632 INFO [-] Loading group to role map definitions from "/opt/stackstorm/rbac/mappings/"
2021-04-27 17:08:45,635 INFO [-] Synchronizing roles...
2021-04-27 17:08:45,645 INFO [-] Roles synchronized (0 created, 1 updated, 0 removed)
2021-04-27 17:08:45,645 INFO [-] Synchronizing users role assignments...
2021-04-27 17:08:45,668 INFO [-] User role assignments synchronized
2021-04-27 17:08:45,670 INFO [-] Synchronizing group to role maps...
2021-04-27 17:08:45,672 INFO [-] Group to role map definitions synchronized.
</code></pre>
<p>After all this when I login as nock to the UI, all the rules are missing.<br>
</p><div class="lightbox-wrapper"><a class="lightbox" href="https://aws1.discourse-cdn.com/standard10/uploads/stackstorm/original/1X/f958c6a5bbf7fda3ab2d5f51114f11712db815e3.png" data-download-href="/uploads/short-url/zzP5GLZhiAd5CiPR52NpMltdamv.png?dl=1" title="no action" rel="noopener nofollow ugc"><img src="https://aws1.discourse-cdn.com/standard10/uploads/stackstorm/optimized/1X/f958c6a5bbf7fda3ab2d5f51114f11712db815e3_2_690x428.png" alt="no action" data-base62-sha1="zzP5GLZhiAd5CiPR52NpMltdamv" width="690" height="428" srcset="https://aws1.discourse-cdn.com/standard10/uploads/stackstorm/optimized/1X/f958c6a5bbf7fda3ab2d5f51114f11712db815e3_2_690x428.png, https://aws1.discourse-cdn.com/standard10/uploads/stackstorm/optimized/1X/f958c6a5bbf7fda3ab2d5f51114f11712db815e3_2_1035x642.png 1.5x, https://aws1.discourse-cdn.com/standard10/uploads/stackstorm/optimized/1X/f958c6a5bbf7fda3ab2d5f51114f11712db815e3_2_1380x856.png 2x" data-small-upload="https://aws1.discourse-cdn.com/standard10/uploads/stackstorm/optimized/1X/f958c6a5bbf7fda3ab2d5f51114f11712db815e3_2_10x10.png"></a></div><p></p>
<p>When I login as st2admin, I see all the rules from the custom pack.</p>
<p>If I uncomment the global permission in normal.yaml, I will see all the rules from all the packs.<br>
</p><div class="lightbox-wrapper"><a class="lightbox" href="https://aws1.discourse-cdn.com/standard10/uploads/stackstorm/original/1X/7f63ffd7b5763b2c15206b8a6933f4dcb2ad635c.png" data-download-href="/uploads/short-url/iaWSXtSTeXH0Fsj3dM6qH9UXvQ0.png?dl=1" title="too much action" rel="noopener nofollow ugc"><img src="https://aws1.discourse-cdn.com/standard10/uploads/stackstorm/optimized/1X/7f63ffd7b5763b2c15206b8a6933f4dcb2ad635c_2_690x406.png" alt="too much action" data-base62-sha1="iaWSXtSTeXH0Fsj3dM6qH9UXvQ0" width="690" height="406" srcset="https://aws1.discourse-cdn.com/standard10/uploads/stackstorm/optimized/1X/7f63ffd7b5763b2c15206b8a6933f4dcb2ad635c_2_690x406.png, https://aws1.discourse-cdn.com/standard10/uploads/stackstorm/optimized/1X/7f63ffd7b5763b2c15206b8a6933f4dcb2ad635c_2_1035x609.png 1.5x, https://aws1.discourse-cdn.com/standard10/uploads/stackstorm/optimized/1X/7f63ffd7b5763b2c15206b8a6933f4dcb2ad635c_2_1380x812.png 2x" data-small-upload="https://aws1.discourse-cdn.com/standard10/uploads/stackstorm/optimized/1X/7f63ffd7b5763b2c15206b8a6933f4dcb2ad635c_2_10x10.png"></a></div><p></p>
<p>I think the problem is with my normal.yaml role config.</p>
<p>If I add the admin role to nock in /opt/stackstorm/rbac/assignments/nock.yaml, I will see all packs, actions, etc. So I think the user part is set up correctly.</p>
<p><strong>How can I ONLY see actions, sensors and rules that are in the twenty20_solutions pack?</strong></p>
            <p><small>2 posts - 1 participant</small></p>
            <p><a href="https://forum.stackstorm.com/t/how-can-i-only-see-actions-sensors-and-rules-that-are-in-the-pack/1670">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/how-can-i-only-see-actions-sensors-and-rules-that-are-in-the-pack/1670</link>
          <pubDate>Tue, 27 Apr 2021 23:43:49 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1670</guid>
          <source url="https://forum.stackstorm.com/t/how-can-i-only-see-actions-sensors-and-rules-that-are-in-the-pack/1670.rss">How can I ONLY see actions, sensors and rules that are in the pack?</source>
        </item>
        <item>
          <title>Installing pack from disk does not include lib/ directory</title>
          <dc:creator><![CDATA[justinm89]]></dc:creator>
          <category>Pack Management</category>
          <description><![CDATA[
            <p>I have a pack (it is a Git repo) that I am attempting to install from disk using<br>
<code>st2 pack install file://&lt;path to pack&gt;</code>. The pack installs successfully, but there is a <code>lib</code> sub-directory within my <code>actions</code> folder that is not moved into <code>/opt/stackstorm/packs</code>.</p>
<p>Below is how my pack is structured on disk before installing:</p>
<pre><code>&gt; pwd
/home/justinm/mypack/actions
&gt; ls -l
-rw-r--r--. 1 root root 470 Mar 24  2021 create_release.py
-rw-r--r--. 1 root root 483 Mar 23 16:08 create_release.yaml
-rw-r--r--. 1 root root   0 Feb  8 23:58 __init__.py
drwxr-xr-x. 2 root root  67 Feb  8 23:58 lib
-rw-r--r--. 1 root root 394 Mar 24  2021 list_releases.py
-rw-r--r--. 1 root root 404 Mar 23 16:13 list_releases.yaml

&gt; ls -l lib
-rw-r--r--. 1 root root 2093 Mar 23 16:11 actions.py
-rw-r--r--. 1 root root    0 Feb  8 23:58 __init__.py
</code></pre>
<p>And here is a snippet from the log from when I installed this pack with the <code>--debug</code> flag:</p>
<pre><code># -------- begin 140499208565520 request ----------
curl -X GET -H  'Connection: keep-alive' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'User-Agent: python-requests/2.14.2' -H  'X-Auth-Token: aacc49af1148409aa9659e4f3d757d66' http://127.0.0.1:9101/v1/packs/mypack
# -------- begin 140499208565520 response ----------
{
    "files": [
        ".gitignore",
        "README.md",
        "config.schema.yaml",
        "icon.png",
        "mypack.yaml.example",
        "pack.yaml",
        "requirements.txt",
        "actions/__init__.py",
        "actions/create_release.py",
        "actions/create_release.yaml",
        "actions/list_releases.py",
        "actions/list_releases.yaml"
    ],
    "name": "mypack",
    "contributors": [],
    "author": "justinm",
    "description": "My test pack",
    "system": {},
    "email": "justinm@foo.bar.com",
    "version": "1.0.0",
    "dependencies": [],
    "keywords": [],
    "path": "/opt/stackstorm/packs/mypack",
    "ref": "mypack",
    "id": "605a5211a54923e4429fbfde",
    "uid": "mypack"
}
</code></pre>
<p>The <code>lib</code> directory is not included in the <code>files</code> list, and it does not exist in <code>/opt/stackstorm/packs</code> either:</p>
<pre><code>&gt; ls -l /opt/stackstorm/packs/mypack/actions
-rwxrwxr-x. 1 root st2packs 470 Mar 24 09:19 create_release.py
-rwxrwxr-x. 1 root st2packs 483 Mar 24 09:19 create_release.yaml
-rwxrwxr-x. 1 root st2packs   0 Mar 24 09:19 __init__.py
-rwxrwxr-x. 1 root st2packs 394 Mar 24 09:19 list_releases.py
-rwxrwxr-x. 1 root st2packs 404 Mar 24 09:19 list_releases.yaml
</code></pre>
<p>My actions are failing because they rely on code in this <code>lib</code> directory. Anyone have any ideas? This <code>lib</code> directory has been committed into my Git repo as well.</p>
            <p><small>4 posts - 2 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/installing-pack-from-disk-does-not-include-lib-directory/1616">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/installing-pack-from-disk-does-not-include-lib-directory/1616</link>
          <pubDate>Wed, 24 Mar 2021 15:35:50 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1616</guid>
          <source url="https://forum.stackstorm.com/t/installing-pack-from-disk-does-not-include-lib-directory/1616.rss">Installing pack from disk does not include lib/ directory</source>
        </item>
        <item>
          <title>How to upgrade installed pack from python2 to python3</title>
          <dc:creator><![CDATA[hgjsj]]></dc:creator>
          <category>Pack Management</category>
          <description><![CDATA[
            <p>Recently, I am going to upgrade Stackstorm to 3.4. From release log，pack with python2 action runner is no longer support? I have 5 packs with python2, and have not certified with python3. I need to upgrade pack to python3 before Stackstorm upgrade.</p>
<p>Could you provide document or instructions for pack upgrade?</p>
            <p><small>2 posts - 2 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/how-to-upgrade-installed-pack-from-python2-to-python3/1611">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/how-to-upgrade-installed-pack-from-python2-to-python3/1611</link>
          <pubDate>Wed, 24 Mar 2021 07:41:03 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1611</guid>
          <source url="https://forum.stackstorm.com/t/how-to-upgrade-installed-pack-from-python2-to-python3/1611.rss">How to upgrade installed pack from python2 to python3</source>
        </item>
        <item>
          <title>Why getting error while installing ansible pack on stackstorm version &quot;st2 3.3.0, on Python 2.7.5&quot;</title>
          <dc:creator><![CDATA[bharat19th]]></dc:creator>
          <category>Pack Management</category>
          <description><![CDATA[
            <p>Hi Guys,</p>
<p>I have installed stackstorm 3.3.0 version on Python 2.7.5 and i want to install Ansible Pack but while installing i am getting below error–</p>
<pre><code>Traceback (most recent call last):
File "/opt/stackstorm/st2/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 334, in &lt;module&gt;
obj.run()
File "/opt/stackstorm/st2/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 193, in run
output = action.run(**self._parameters)
File "/opt/stackstorm/packs/packs/actions/pack_mgmt/download.py", line 86, in run
logger=self.logger)
File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/util/pack_management.py", line 165, in download_pack
verify_pack_version(pack_metadata=pack_metadata, use_python3=use_python3)
File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/util/pack_management.py", line 464, in verify_pack_version
raise ValueError(msg)
ValueError: Pack "ansible" requires Python 3.x, but current Python version is "2.7.5". You can override this restriction by providing the "force" flag, but the pack is not guaranteed to work.
</code></pre>
<p>after the googling even i tried to install with --force flag but installation is getting timeout here is output…</p>
<pre><code>[root@stackstorm-2 packs]# st2 pack install ansible --force
For the "ansible" pack, the following content will be registered:
rules     |  0
sensors   |  0
triggers  |  0
actions   |  8
aliases   |  0
Installation may take a while for packs with many items.
        [ succeeded ] init_task
        [ succeeded ] download_pack
        [ succeeded ] make_a_prerun
        [ succeeded ] get_pack_dependencies
        [ succeeded ] check_dependency_and_conflict_list
        [  timeout  ] install_pack_requirements
id: 6054f442cc9b23f2f2c47796
action.ref: packs.install
parameters:
  force: true
  packs:
  - ansible
  python3: false
status: failed
start_timestamp: Fri, 19 Mar 2021 18:58:10 UTC
end_timestamp: Fri, 19 Mar 2021 19:09:33 UTC
result:
  errors: []
  output:
    conflict_list: []
    message: ''
    packs_list:
    - ansible
    warning_list: null
+--------------------------+-------------------------+------------------------------+-----------------------------+-------------------------------+
| id                       | status                  | task                         | action                      | start_timestamp               |
+--------------------------+-------------------------+------------------------------+-----------------------------+-------------------------------+
| 6054f443b8d4a06354e7e968 | succeeded (0s elapsed)  | init_task                    | core.noop                   | Fri, 19 Mar 2021 18:58:11 UTC |
| 6054f443b8d4a06354e7e978 | succeeded (57s elapsed) | download_pack                | packs.download              | Fri, 19 Mar 2021 18:58:11 UTC |
| 6054f47db8d4a06354e7e988 | succeeded (13s elapsed) | make_a_prerun                | packs.virtualenv_prerun     | Fri, 19 Mar 2021 18:59:09 UTC |
| 6054f48bb8d4a06354e7e998 | succeeded (7s elapsed)  | get_pack_dependencies        | packs.get_pack_dependencies | Fri, 19 Mar 2021 18:59:23 UTC |
| 6054f493b8d4a06354e7e9a8 | succeeded (0s elapsed)  | check_dependency_and_conflic | core.noop                   | Fri, 19 Mar 2021 18:59:31 UTC |
|                          |                         | t_list                       |                             |                               |
| 6054f494b8d4a06354e7e9b8 | timeout (600s elapsed)  | install_pack_requirements    | packs.setup_virtualenv      | Fri, 19 Mar 2021 18:59:32 UTC |
+--------------------------+-------------------------+------------------------------+-----------------------------+-------------------------------+
[root@stackstorm-2 packs]#
</code></pre>
<p>cam someone please help me with pointers to fix this issue?</p>
<p>Thanks</p>
            <p><small>6 posts - 3 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/why-getting-error-while-installing-ansible-pack-on-stackstorm-version-st2-3-3-0-on-python-2-7-5/1605">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/why-getting-error-while-installing-ansible-pack-on-stackstorm-version-st2-3-3-0-on-python-2-7-5/1605</link>
          <pubDate>Sat, 20 Mar 2021 16:50:12 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1605</guid>
          <source url="https://forum.stackstorm.com/t/why-getting-error-while-installing-ansible-pack-on-stackstorm-version-st2-3-3-0-on-python-2-7-5/1605.rss">Why getting error while installing ansible pack on stackstorm version &quot;st2 3.3.0, on Python 2.7.5&quot;</source>
        </item>
        <item>
          <title>St2packs not building properly on Mac under Docker 20.10.5</title>
          <dc:creator><![CDATA[lordpengwin]]></dc:creator>
          <category>Pack Management</category>
          <description><![CDATA[
            <p>I’ve been having a problem recently with building the st2packs in a Mac. It seems that the builder stage of the Dockerfile is not getting executed. After a lot of trial and error, we determined that the only way to get it to work was to add something like the last line here to the Dockerfile</p>
<blockquote>
<p>FROM stackstorm/st2packs:builder AS builder</p>
<p>RUN /opt/stackstorm/st2/bin/st2-pack-install “aws”</p>
<p>FROM stackstorm/st2packs:runtime<br>
COPY --from=builder /opt/stackstorm/packs /opt/stackstorm/packs</p>
</blockquote>
<p>It seems that unless you explicitly reference the builder stage it does not get executed even though it is referenced in an ONBUILD clause in the runtime Dockerfile. I don’t know if this is specific to the Mac or due to some new change in Docker but we had the same problem on multiple machines.</p>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://forum.stackstorm.com/t/st2packs-not-building-properly-on-mac-under-docker-20-10-5/1600">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/st2packs-not-building-properly-on-mac-under-docker-20-10-5/1600</link>
          <pubDate>Thu, 18 Mar 2021 16:01:07 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1600</guid>
          <source url="https://forum.stackstorm.com/t/st2packs-not-building-properly-on-mac-under-docker-20-10-5/1600.rss">St2packs not building properly on Mac under Docker 20.10.5</source>
        </item>
        <item>
          <title>Need help with remote debugging</title>
          <dc:creator><![CDATA[badchad]]></dc:creator>
          <category>Pack Management</category>
          <description><![CDATA[
            <p>Can someone help me understand how to remotely debug Stackstorm? I have tried 10 different ways and nothing pans out.  I do have intellij as well.</p>
            <p><small>5 posts - 2 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/need-help-with-remote-debugging/1571">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/need-help-with-remote-debugging/1571</link>
          <pubDate>Tue, 23 Feb 2021 23:17:49 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1571</guid>
          <source url="https://forum.stackstorm.com/t/need-help-with-remote-debugging/1571.rss">Need help with remote debugging</source>
        </item>
        <item>
          <title>Unable to Install Packs From GUI without specifying Python3 in command line</title>
          <dc:creator><![CDATA[vicaran]]></dc:creator>
          <category>Pack Management</category>
          <description><![CDATA[
            <p>Hi,</p>
<p>I installed StackStorm on RedHat7. But, when downloading packs through the command line, I get the following error for all packs</p>
<p>Pack “xxx” requires Python 3.x, but current Python version is “2.7.5”. You can override this restriction by providing the “force” flag, but the pack is not guaranteed to work</p>
<p>However, if I specify st2 pack install xxx --python3, it installs fine. This prevents me from installing packs through the GUI. I was wondering if anyone is facing the same problem and has a solution. I have both python 2.7 and python 3.6 installed.</p>
            <p><small>5 posts - 3 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/unable-to-install-packs-from-gui-without-specifying-python3-in-command-line/1570">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/unable-to-install-packs-from-gui-without-specifying-python3-in-command-line/1570</link>
          <pubDate>Tue, 23 Feb 2021 07:32:50 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1570</guid>
          <source url="https://forum.stackstorm.com/t/unable-to-install-packs-from-gui-without-specifying-python3-in-command-line/1570.rss">Unable to Install Packs From GUI without specifying Python3 in command line</source>
        </item>
        <item>
          <title>Stackstorm installed with pytjon 2.7, but need to use python3.6 libraries in Stackstorm sensor</title>
          <dc:creator><![CDATA[sp4]]></dc:creator>
          <category>Pack Management</category>
          <description><![CDATA[
            <p>Hi,</p>
<p>We have developed a version of our Stackstorm pack and other objects in Stackstorm Version 3.2 installed on a system that has stackstorm with Python 2.7.5</p>
<p>But now as part of our upgrade process, we are planning to use Python 3.6 instead of 2.7 version.<br>
For this</p>
<ol>
<li>We installed stackstorm 3.3 and default python 2.7.5 and python3 3.6.8.</li>
<li>mannually placed all the python python3.6 libraries into /opt/stackstorm/st2/lib/ folder.</li>
<li>We modified our Pack.yaml files to point to Python 3 , and forced to install using python3 virtual environment.</li>
</ol>
<p>Issue: After making the changes we are getting the following error:<br>
Virtual environment (/opt/stackstorm/virtualenvs/servicenow_pack) for pack “servicenow_pack” is using Python 3.<br>
Using Python 3 virtual environments in mixed deployments is only supported for Python runner<br>
actions and not sensors. If you want to run this sensor, please re-recreate the<br>
virtual environment with python2 binary:<br>
“st2 run packs.setup_virtualenv packs=servicenow_pack python3=false”</p>
<p>Also attached the full error:<br>
</p><div class="lightbox-wrapper"><a class="lightbox" href="https://aws1.discourse-cdn.com/standard10/uploads/stackstorm/original/1X/527ce63d7288f9464d4fcf9e6a276c80b3b2f14d.png" data-download-href="/uploads/short-url/bLIKohQvjDDYTXJvNPGxs1V7PAh.png?dl=1" title="err" rel="noopener nofollow ugc"><img src="https://aws1.discourse-cdn.com/standard10/uploads/stackstorm/optimized/1X/527ce63d7288f9464d4fcf9e6a276c80b3b2f14d_2_690x331.png" alt="err" data-base62-sha1="bLIKohQvjDDYTXJvNPGxs1V7PAh" width="690" height="331" srcset="https://aws1.discourse-cdn.com/standard10/uploads/stackstorm/optimized/1X/527ce63d7288f9464d4fcf9e6a276c80b3b2f14d_2_690x331.png, https://aws1.discourse-cdn.com/standard10/uploads/stackstorm/optimized/1X/527ce63d7288f9464d4fcf9e6a276c80b3b2f14d_2_1035x496.png 1.5x, https://aws1.discourse-cdn.com/standard10/uploads/stackstorm/optimized/1X/527ce63d7288f9464d4fcf9e6a276c80b3b2f14d_2_1380x662.png 2x" data-small-upload="https://aws1.discourse-cdn.com/standard10/uploads/stackstorm/optimized/1X/527ce63d7288f9464d4fcf9e6a276c80b3b2f14d_2_10x10.png"></a></div><p></p>
<p>Thanks</p>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://forum.stackstorm.com/t/stackstorm-installed-with-pytjon-2-7-but-need-to-use-python3-6-libraries-in-stackstorm-sensor/1541">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/stackstorm-installed-with-pytjon-2-7-but-need-to-use-python3-6-libraries-in-stackstorm-sensor/1541</link>
          <pubDate>Tue, 19 Jan 2021 16:53:37 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1541</guid>
          <source url="https://forum.stackstorm.com/t/stackstorm-installed-with-pytjon-2-7-but-need-to-use-python3-6-libraries-in-stackstorm-sensor/1541.rss">Stackstorm installed with pytjon 2.7, but need to use python3.6 libraries in Stackstorm sensor</source>
        </item>
        <item>
          <title>ServiceNow pack PySnow library deprecation warnings</title>
          <dc:creator><![CDATA[TimothyDJones]]></dc:creator>
          <category>Pack Management</category>
          <description><![CDATA[
            <p>Hello! New to the forum and to Stackstorm, so please forgive any faux pas. I appreciate any guidance about etiquette and rules, as appropriate. <img src="https://emoji.discourse-cdn.com/apple/slight_smile.png?v=9" title=":slight_smile:" class="emoji" alt=":slight_smile:"></p>
<p>I’m using the <a href="https://github.com/StackStorm-Exchange/stackstorm-servicenow/" rel="noopener nofollow ugc">ServiceNow pack from Stackstorm Exchange</a> with version 3.2.0 of Stackstorm and whenever I run most any action, the <a href="https://github.com/rbw/pysnow/" rel="noopener nofollow ugc">PySnow library</a> that it’s based on returns a deprecation warning:</p>
<pre><code class="lang-auto">  "stderr": "/opt/stackstorm/virtualenvs/servicenow/lib/python2.7/site-packages/pysnow/client.py:120: DeprecationWarning: `query` is deprecated and will be removed in a future release. Please use `resource()` instead.
  \"Please use `resource()` instead.\" % inspect.stack()[1][3], DeprecationWarning)
/opt/stackstorm/virtualenvs/servicenow/lib/python2.7/site-packages/pysnow/legacy_request.py:99: DeprecationWarning: get_all() is deprecated, please use get_multiple() instead
  warnings.warn(\"get_all() is deprecated, please use get_multiple() instead\", DeprecationWarning)
",
  "exit_code": 0
</code></pre>
<p>I was considering forking the pack and adding a configuration parameter for the <code>/api/now/</code> “version” for the ServiceNow API and then updating the pack action Python methods to call the “newer” methods based on the configuration parameter (i.e., “strategy” pattern). Would that be the appropriate approach? (Of course, I would submit a pull request for the updated code to share with community. I just wasn’t sure of philosophy.)</p>
<p>Thanks!<br>
Tim Jones</p>
            <p><small>3 posts - 2 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/servicenow-pack-pysnow-library-deprecation-warnings/1536">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/servicenow-pack-pysnow-library-deprecation-warnings/1536</link>
          <pubDate>Fri, 15 Jan 2021 21:18:47 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1536</guid>
          <source url="https://forum.stackstorm.com/t/servicenow-pack-pysnow-library-deprecation-warnings/1536.rss">ServiceNow pack PySnow library deprecation warnings</source>
        </item>
        <item>
          <title>Stackstorm sensor on docker-compose not able to install</title>
          <dc:creator><![CDATA[sp4]]></dc:creator>
          <category>Pack Management</category>
          <description><![CDATA[
            <p>I have installed stackstorm on docker-compose. And I am trying to setup a sensor that polls a unix folder. I am able to create a shared folder that is shared within the docker and outside. But somehow when i install the docker the rule says missing trigger. The sensor will not be installed . Not sure how to proceed</p>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://forum.stackstorm.com/t/stackstorm-sensor-on-docker-compose-not-able-to-install/1530">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/stackstorm-sensor-on-docker-compose-not-able-to-install/1530</link>
          <pubDate>Wed, 06 Jan 2021 13:40:43 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1530</guid>
          <source url="https://forum.stackstorm.com/t/stackstorm-sensor-on-docker-compose-not-able-to-install/1530.rss">Stackstorm sensor on docker-compose not able to install</source>
        </item>
        <item>
          <title>Dependency in sensor&#39;s venv intersects with stackstorm internal python package</title>
          <dc:creator><![CDATA[insomnes]]></dc:creator>
          <category>Pack Management</category>
          <description><![CDATA[
            <p>Hello!<br>
I have “cryptography” module dependency in my sensor. I’ve installed proper version of this library into my pack’s virtual environment.<br>
But i’ve found that loaded version is from st2 sensor container environment.<br>
Is there any way to totally isolate pack’s venv?<br>
Module reloading is not very helpful cause there a lot of submodules intersection in this library and also versions of C-bindings are in mismatch.</p>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://forum.stackstorm.com/t/dependency-in-sensors-venv-intersects-with-stackstorm-internal-python-package/1521">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/dependency-in-sensors-venv-intersects-with-stackstorm-internal-python-package/1521</link>
          <pubDate>Thu, 31 Dec 2020 08:29:58 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1521</guid>
          <source url="https://forum.stackstorm.com/t/dependency-in-sensors-venv-intersects-with-stackstorm-internal-python-package/1521.rss">Dependency in sensor&#39;s venv intersects with stackstorm internal python package</source>
        </item>
        <item>
          <title>How to install pack from private git repository using ssh when deployed on docker</title>
          <dc:creator><![CDATA[wajih-ats]]></dc:creator>
          <category>Pack Management</category>
          <description><![CDATA[
            <p>Hi guys<br>
I’m having trouble with ssh when i try to install pack from private repo using docker;</p>
<ul>
<li>which container should contain the ssh key (st2client or st2actionrunner or st2api) ?</li>
<li>which user should be owner (stanley or root)</li>
</ul>
<p>If it’s possible to put this in the documentation or in the readme file it would be very helpfull<br>
Thanks</p>
            <p><small>3 posts - 2 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/how-to-install-pack-from-private-git-repository-using-ssh-when-deployed-on-docker/1500">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/how-to-install-pack-from-private-git-repository-using-ssh-when-deployed-on-docker/1500</link>
          <pubDate>Tue, 08 Dec 2020 09:16:33 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1500</guid>
          <source url="https://forum.stackstorm.com/t/how-to-install-pack-from-private-git-repository-using-ssh-when-deployed-on-docker/1500.rss">How to install pack from private git repository using ssh when deployed on docker</source>
        </item>
        <item>
          <title>Stackstorm-icinga2 - Exception from data gathered by Sensor</title>
          <dc:creator><![CDATA[thozook]]></dc:creator>
          <category>Pack Management</category>
          <description><![CDATA[
            <p>Hello All,</p>
<p>I’m attempting to setup <a href="https://github.com/StackStorm-Exchange/stackstorm-icinga2" class="inline-onebox" rel="noopener nofollow ugc">GitHub - StackStorm-Exchange/stackstorm-icinga2: Icinga2 Integration pack</a> and after setting up a rule in the Stackstorm UI, I noticed it would never get enforced.</p>
<p>Running the sensor with “/opt/stackstorm/st2/bin/st2sensorcontainer --config-file=/etc/st2/st2.conf --sensor-ref=icinga2.Icinga2StateChangeSensor” as root reveals that many of the detected state changes are causing exceptions in the sensor and thus are not dispatching the trigger. Example state changes causing exceptions below:</p>
<p>Exception Example 1:</p>
<pre><code>2020-09-17 10:20:52,526 INFO [-] Connecting to event stream API.
2020-09-17 10:20:52,718 INFO [-] Processing event: {"check_result":{"active":true,"check_source":"###HOSTNAME###","command":["C:\Program Files\ICINGA2\/sbin/check_load.exe","-c","95","-w","90"],"execution_end":1600363364.508,"execution_start":1600363362.94,"exit_status":2.0,"output":"LOAD CRITICAL 97.28% ","performance_data":["load=97.28%;90;95;0;100"],"schedule_end":1600363364.512,"schedule_start":1600363364.512,"state":2.0,"ttl":0.0,"type":"CheckResult","vars_after":{"attempt":1.0,"reachable":true,"state":2.0,"state_type":0.0},"vars_before":{"attempt":1.0,"reachable":true,"state":0.0,"state_type":1.0}},"host":"###HOSTNAME###","service":"Windows Load","state":2.0,"state_type":0.0,"timestamp":1600363363.52031,"type":"StateChange"}
2020-09-17 10:20:52,719 ERROR [-] Icinga2StateChangeSensor Exception Invalid \escape: line 1 column 92 (char 91)
Traceback (most recent call last):
  File "/opt/stackstorm/packs/icinga2/sensors/icinga2_state_change_events.py", line 66, in run
    self.process_event(event)
  File "/opt/stackstorm/packs/icinga2/sensors/icinga2_state_change_events.py", line 76, in process_event
    event = json.loads(event)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid \escape: line 1 column 92 (char 91)
2020-09-17 10:20:57,721 INFO [-] Connecting to event stream API.
</code></pre>
<p>Exception Example 2:</p>
<pre><code>2020-09-17 10:29:03,692 INFO [-] Connecting to event stream API.
2020-09-17 10:29:29,318 INFO [-] Processing event: {"check_result":{"active":true,"check_source":"###HOSTNAME###","command":["C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe","-command","C:\Program` Files\ICINGA2\sbin\JobStatus.ps1","-Username","###USERNAME###","-Password","###PASSWORD###","; exit","$LASTEXITCODE"],"execution_end":1600363880.88,"execution_start":1600363878.467,"exit_status":0.0,"output":"OK: All Jobs have an EndTime Entry. ","performance_data":["EndTimeNullCount=0"],"schedule_end":1600363880.88,"schedule_start":1600363880.88,"state":0.0,"ttl":0.0,"type":"CheckResult","vars_after":{"attempt":1.0,"reachable":true,"state":0.0,"state_type":1.0},"vars_before":{"attempt":2.0,"reachable":true,"state":2.0,"state_type":0.0}},"host":"###HOSTNAME###","service":"Job Monitor","state":0.0,"state_type":1.0,"timestamp":1600363880.058318,"type":"StateChange"}
2020-09-17 10:29:29,320 ERROR [-] Icinga2StateChangeSensor Exception Invalid \escape: line 1 column 89 (char 88)
Traceback (most recent call last):
  File "/opt/stackstorm/packs/icinga2/sensors/icinga2_state_change_events.py", line 66, in run
    self.process_event(event)
  File "/opt/stackstorm/packs/icinga2/sensors/icinga2_state_change_events.py", line 76, in process_event
    event = json.loads(event)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid \escape: line 1 column 89 (char 88)
2020-09-17 10:29:34,322 INFO [-] Connecting to event stream API.
</code></pre>
<p>Has anyone encountered this before and been able to resolve/work around this?</p>
            <p><small>2 posts - 2 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/stackstorm-icinga2-exception-from-data-gathered-by-sensor/1422">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/stackstorm-icinga2-exception-from-data-gathered-by-sensor/1422</link>
          <pubDate>Thu, 17 Sep 2020 18:09:02 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1422</guid>
          <source url="https://forum.stackstorm.com/t/stackstorm-icinga2-exception-from-data-gathered-by-sensor/1422.rss">Stackstorm-icinga2 - Exception from data gathered by Sensor</source>
        </item>
        <item>
          <title>(action file most likely doesn&#39;t exist or contains invalid syntax): No module named cx_Oracle</title>
          <dc:creator><![CDATA[Biji]]></dc:creator>
          <category>Pack Management</category>
          <description><![CDATA[
            <p>Hi all, pretty new to stackstorm, I was making a custom pack on stackstorm for a oracle use case in stackstorm, tried all sought of things but no luck.<br>
Pack is been made just during execution getting an error for this.</p>
<h1>st2 execution get 5f5904b5e6db36c03ea812db</h1>
<p>id: 5f5904b5e6db36c03ea812db<br>
action.ref: oracle_test.Oracledbcheck<br>
context.user: st2admin<br>
parameters:<br>
DBName: ****<br>
Hostname: ****<br>
Password: *****<br>
Port: ‘1526’<br>
ServiceName:****<br>
Username:*****<br>
log_level: DEBUG<br>
status: failed (1s elapsed)<br>
start_timestamp: Wed, 09 Sep 2020 16:37:08 UTC<br>
end_timestamp: Wed, 09 Sep 2020 16:37:09 UTC<br>
result:<br>
exit_code: 1<br>
result: None<br>
stderr: "Traceback (most recent call last):<br>
File “/opt/stackstorm/st2/lib/python2.7/site-packages/python_runner/python_action_wrapper.py”, line 333, in<br>
obj.run()<br>
File “/opt/stackstorm/st2/lib/python2.7/site-packages/python_runner/python_action_wrapper.py”, line 191, in run<br>
action = self._get_action_instance()<br>
File “/opt/stackstorm/st2/lib/python2.7/site-packages/python_runner/python_action_wrapper.py”, line 244, in _get_action_instance<br>
raise exc_cls(msg)<br>
ImportError: Failed to load action class from file “/opt/stackstorm/packs/oracle_test/actions/Oracledbcheck.py” (action file most likely doesn’t exist or contains invalid syntax): No module named cx_Oracle</p>
<p>Traceback (most recent call last):<br>
File “/opt/stackstorm/st2/lib/python2.7/site-packages/python_runner/python_action_wrapper.py”, line 237, in _get_action_instance<br>
actions_cls = action_loader.register_plugin(Action, self._file_path)<br>
File “/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/util/loader.py”, line 167, in register_plugin<br>
module = imp.load_source(module_name, plugin_abs_file_path)<br>
File “/opt/stackstorm/packs/oracle_test/actions/Oracledbcheck.py”, line 3, in<br>
import cx_Oracle<br>
ImportError: No module named cx_Oracle</p>
<p>it has the cx_oracle installed on the machine.<br>
Most likely seems stackstorm isn’t picking it up.</p>
<p>Any suggestion???</p>
            <p><small>4 posts - 3 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/action-file-most-likely-doesnt-exist-or-contains-invalid-syntax-no-module-named-cx-oracle/1411">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/action-file-most-likely-doesnt-exist-or-contains-invalid-syntax-no-module-named-cx-oracle/1411</link>
          <pubDate>Thu, 10 Sep 2020 06:33:17 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1411</guid>
          <source url="https://forum.stackstorm.com/t/action-file-most-likely-doesnt-exist-or-contains-invalid-syntax-no-module-named-cx-oracle/1411.rss">(action file most likely doesn&#39;t exist or contains invalid syntax): No module named cx_Oracle</source>
        </item>
        <item>
          <title>Need to implement stackstorm actions</title>
          <dc:creator><![CDATA[Narendra4st2]]></dc:creator>
          <category>Pack Management</category>
          <description><![CDATA[
            <p>Hi,</p>
<p>I am new to stackstorm and Kindly help me on the below requirement.</p>
<p>Manual Process:<br>
step1: We are logging into  a server using user credentials<br>
step2: switching to docker user using: sudo su - docker  (it is not asking password)<br>
Step3: Now executing the commands:<br>
systemctl start docker<br>
systemctl stop docker<br>
systemctl restart docker</p>
<p>I know we can use remote shell command runner type for the action but how to switch to docker user from user and run above commands.</p>
            <p><small>3 posts - 2 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/need-to-implement-stackstorm-actions/1298">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/need-to-implement-stackstorm-actions/1298</link>
          <pubDate>Mon, 29 Jun 2020 14:55:05 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1298</guid>
          <source url="https://forum.stackstorm.com/t/need-to-implement-stackstorm-actions/1298.rss">Need to implement stackstorm actions</source>
        </item>
        <item>
          <title>Any pack installation fails during registration</title>
          <dc:creator><![CDATA[piyush.a]]></dc:creator>
          <category>Pack Management</category>
          <description><![CDATA[
            <p>I am trying to install packs but they all fail at registration</p>
<p>2020-03-03 17:53:50,790  WARNING - Locale unknown with encoding unknown which is not UTF-8 is used. This means that some functionality which relies on outputting unicode characters won’t work. You are encouraged to use UTF-8 locale by setting LC_ALL environment variable to en_US.UTF-8 or similar.</p>
<pre><code>[ succeeded ] download pack
[ succeeded ] make a prerun
[ succeeded ] install pack dependencies
[  failed   ] register pack
</code></pre>
<p>id: 5e5e4c577f704d773feec2d3<br>
action.ref: packs.install<br>
parameters:<br>
packs:</p>
<ul>
<li>nagios=0.1.0<br>
python3: false<br>
status: failed<br>
result_task: register pack<br>
result:<br>
exit_code: 1<br>
result: None<br>
stderr: "st2.actions.python.St2RegisterAction: DEBUG    Calling client method “register” with kwargs “{‘types’: [u’all’], ‘packs’: [u’nagios’]}”<br>
Traceback (most recent call last):<br>
File “/opt/stackstorm/st2/lib/python2.7/site-packages/python_runner/python_action_wrapper.py”, line 333, in <br>
obj.run()<br>
File “/opt/stackstorm/st2/lib/python2.7/site-packages/python_runner/python_action_wrapper.py”, line 192, in run<br>
output = action.run(**self._parameters)<br>
File “/opt/stackstorm/packs/packs/actions/pack_mgmt/register.py”, line 80, in run<br>
format_func=format_result)<br>
File “/opt/stackstorm/packs/packs/actions/pack_mgmt/register.py”, line 148, in _run_client_method<br>
result = method(**method_kwargs)<br>
File “/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py”, line 41, in decorate<br>
return func(*args, **kwargs)<br>
File “/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py”, line 548, in register<br>
response = self.client.post(url, payload, **kwargs)<br>
File “/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/utils/httpclient.py”, line 32, in decorate<br>
return func(*args, **kwargs)<br>
File “/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/utils/httpclient.py”, line 50, in decorate<br>
return func(*args, **kwargs)<br>
File “/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/utils/httpclient.py”, line 60, in decorate<br>
return func(*args, **kwargs)<br>
File “/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/utils/httpclient.py”, line 95, in post<br>
response = requests.post(self.root + url, json.dumps(data), **kwargs)<br>
File “/opt/stackstorm/st2/lib/python2.7/site-packages/requests/api.py”, line 116, in post<br>
return request(‘post’, url, data=data, json=json, **kwargs)<br>
File “/opt/stackstorm/st2/lib/python2.7/site-packages/requests/api.py”, line 60, in request<br>
return session.request(method=method, url=url, **kwargs)<br>
File “/opt/stackstorm/st2/lib/python2.7/site-packages/requests/sessions.py”, line 533, in request<br>
resp = self.send(prep, **send_kwargs)<br>
File “/opt/stackstorm/st2/lib/python2.7/site-packages/requests/sessions.py”, line 646, in send<br>
r = adapter.send(request, **kwargs)<br>
File “/opt/stackstorm/st2/lib/python2.7/site-packages/requests/adapters.py”, line 516, in send<br>
raise ConnectionError(e, request=request)<br>
requests.exceptions.ConnectionError: HTTPSConnectionPool(host=‘<a href="http://myhost.examples.com" rel="nofollow noopener">myhost.examples.com</a>’, port=443): Max retries exceeded with url: /api/v1/packs/register (Caused by NewConnectionError(’&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f0c6378c2d0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known’,))<br>
"<br>
stdout: ‘’<br>
error: st2.actions.python.St2RegisterAction: DEBUG    Calling client method “register” with kwargs “{‘types’: [u’all’], ‘packs’: [u’nagios’]}”<br>
Traceback (most recent call last):<br>
File “/opt/stackstorm/st2/lib/python2.7/site-packages/python_runner/python_action_wrapper.py”, line 333, in <br>
obj.run()<br>
File “/opt/stackstorm/st2/lib/python2.7/site-packages/python_runner/python_action_wrapper.py”, line 192, in run<br>
output = action.run(**self._parameters)<br>
File “/opt/stackstorm/packs/packs/actions/pack_mgmt/register.py”, line 80, in run<br>
format_func=format_result)<br>
File “/opt/stackstorm/packs/packs/actions/pack_mgmt/register.py”, line 148, in _run_client_method<br>
result = method(**method_kwargs)<br>
File “/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py”, line 41, in decorate<br>
return func(*args, **kwargs)<br>
File “/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py”, line 548, in register<br>
response = self.client.post(url, payload, **kwargs)<br>
File “/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/utils/httpclient.py”, line 32, in decorate<br>
return func(*args, **kwargs)<br>
File “/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/utils/httpclient.py”, line 50, in decorate<br>
return func(*args, **kwargs)<br>
File “/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/utils/httpclient.py”, line 60, in decorate<br>
return func(*args, **kwargs)<br>
File “/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/utils/httpclient.py”, line 95, in post<br>
response = requests.post(self.root + url, json.dumps(data), **kwargs)<br>
File “/opt/stackstorm/st2/lib/python2.7/site-packages/requests/api.py”, line 116, in post<br>
return request(‘post’, url, data=data, json=json, **kwargs)<br>
File “/opt/stackstorm/st2/lib/python2.7/site-packages/requests/api.py”, line 60, in request<br>
return session.request(method=method, url=url, **kwargs)<br>
File “/opt/stackstorm/st2/lib/python2.7/site-packages/requests/sessions.py”, line 533, in request<br>
resp = self.send(prep, **send_kwargs)<br>
File “/opt/stackstorm/st2/lib/python2.7/site-packages/requests/sessions.py”, line 646, in send<br>
r = adapter.send(request, **kwargs)<br>
File “/opt/stackstorm/st2/lib/python2.7/site-packages/requests/adapters.py”, line 516, in send<br>
raise ConnectionError(e, request=request)<br>
requests.exceptions.ConnectionError: HTTPSConnectionPool(host=‘<a href="http://myhost.examples.com" rel="nofollow noopener">myhost.examples.com</a>’, port=443): Max retries exceeded with url: /api/v1/packs/register (Caused by NewConnectionError(’&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f0c6378c2d0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known’,))</li>
</ul>
<p>traceback: None<br>
failed_on: register pack<br>
start_timestamp: Tue, 03 Mar 2020 12:23:51 UTC<br>
end_timestamp: Tue, 03 Mar 2020 12:24:03 UTC<br>
±-------------------------±-----------------------±---------------------±---------------------±-----------------+<br>
| id                       | status                 | task                 | action               | start_timestamp  |<br>
±-------------------------±-----------------------±---------------------±---------------------±-----------------+<br>
| 5e5e4c577f704d751ad7ad78 | succeeded (5s elapsed) | download pack        | packs.download       | Tue, 03 Mar 2020 |<br>
|                          |                        |                      |                      | 12:23:51 UTC     |<br>
| 5e5e4c5d7f704d751ad7ad7a | succeeded (1s elapsed) | make a prerun        | packs.virtualenv_pre | Tue, 03 Mar 2020 |<br>
|                          |                        |                      | run                  | 12:23:57 UTC     |<br>
| 5e5e4c5e7f704d751ad7ad7c | succeeded (3s elapsed) | install pack         | packs.setup_virtuale | Tue, 03 Mar 2020 |<br>
|                          |                        | dependencies         | nv                   | 12:23:58 UTC     |<br>
| 5e5e4c627f704d751ad7ad7e | failed (0s elapsed)    | register pack        | packs.load           | Tue, 03 Mar 2020 |<br>
|                          |                        |                      |                      | 12:24:02 UTC     |<br>
±-------------------------±-----------------------±---------------------±---------------------±-----------------+</p>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://forum.stackstorm.com/t/any-pack-installation-fails-during-registration/1088">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/any-pack-installation-fails-during-registration/1088</link>
          <pubDate>Tue, 03 Mar 2020 12:30:30 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1088</guid>
          <source url="https://forum.stackstorm.com/t/any-pack-installation-fails-during-registration/1088.rss">Any pack installation fails during registration</source>
        </item>
  </channel>
</rss>
